# -*- coding: utf-8 -*-
"""Flask_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rk5pk03DIoEJr16pn8FctuNGHOVPQup7
"""

import webbrowser
from flask import Flask, render_template, request
import pickle

app = Flask(__name__)

def detection(model, x):
    riesgo = model.predict([x])[0]
    if riesgo == 1:
        riesgo = 'Bajo'
    elif riesgo ==2:
        riesgo = 'Alto'
    return riesgo

@app.route('/', methods=['POST', 'GET'])
def main_app():
    try:
        if request.method == 'POST':
            dia_semana = request.form['dia_semana']
            latitud = request.form['latitud']
            longitud = request.form['longitud']
            mes = request.form['mes']
            hora = request.form['hora']
            minuto = request.form['minuto']
            parametros = (dia_semana, latitud, longitud, mes, hora, minuto)
            lang = detection(model, parametros)
        else:
            lang = None
        return render_template('index.html', result={'riesgo': lang.upper()})
    except:
        return render_template('index.html', result={'riesgo': None})

if __name__ == '__main__':
    with open('Modelo/modelo2.pkl', 'rb') as r:
        model = pickle.load(r)
    url = "http://localhost:5000"
    webbrowser.open_new(url)
    app.run()

